[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mptool"
version = "1!0.0.1787109864"
description = "messagepack functions for typed CLI IPC"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "msgpack",
    "epprint @ git+https://github.com/jakeogh/epprint@a99435a96f6cc399b1cab858f1019e328687d2d1",
]
license = "ISC"
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/jakeogh/mptool"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
mptool = [
    "py.typed",
]
